spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/empresas_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}

#debug enable
spring.jpa.properties.hibernate.generate_statistics=true