spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/empresas_db
spring.datasource.username=postgres
spring.datasource.password=hansel10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#debug enable
spring.jpa.properties.hibernate.generate_statistics=true